# Generated by Django 4.1 on 2023-11-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
