# Generated by Django 4.1 on 2023-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='capacidad_dormir',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='capacidad_viajar',
            field=models.IntegerField(default=0),
        ),
    ]
