# Generated by Django 4.1 on 2023-11-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_remove_oferta_producto'),
        ('producto', '0003_producto_capacidad_dormir_producto_capacidad_viajar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oferta.oferta'),
        ),
    ]
