# Generated by Django 4.1 on 2023-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('integral', 'Autocaravana Integral'), ('capuchina', 'Autocaravana Capuchina'), ('perfilada', 'Autocaravana Perfilada'), ('camper', 'Autocaravana Camper')], default='integral', max_length=20),
        ),
    ]
