# Generated by Django 4.1 on 2023-11-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='opiniones',
            field=models.TextField(blank=True),
        ),
    ]
