# Generated by Django 4.1 on 2023-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_opiniones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='opiniones',
            field=models.CharField(blank=True, default=',', max_length=1000),
        ),
    ]
