# Generated by Django 4.1 on 2023-11-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_categoria'),
        ('producto', '0006_alter_producto_opiniones'),
    ]

    operations = [
    ]
