# Generated by Django 4.1 on 2023-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_merge_20231121_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
