# Generated by Django 4.1 on 2023-11-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='producto',
        ),
    ]
