# Generated by Django 4.1 on 2023-12-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0003_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
