# Generated by Django 4.1 on 2023-11-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion_envio', models.TextField()),
                ('direccion_facturacion', models.TextField()),
                ('instrucciones_entrega', models.TextField()),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cesta.carrito')),
            ],
        ),
    ]
