# Generated by Django 4.1 on 2023-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0002_datospedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospedido',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='datospedido',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='datospedido',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
