# Generated by Django 4.1 on 2023-11-20 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0003_datospedido_email_datospedido_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospedido',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesta.carrito'),
        ),
        migrations.AlterField(
            model_name='datospedido',
            name='direccion_envio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datospedido',
            name='direccion_facturacion',
            field=models.CharField(max_length=150),
        ),
    ]
