# Generated by Django 4.1 on 2023-11-20 10:31

import cesta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0004_alter_datospedido_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospedido',
            name='forma_entrega',
            field=models.CharField(choices=[(cesta.models.FormaEntrega['ESTANDAR'], 'Estándar'), (cesta.models.FormaEntrega['URGENTE'], 'Urgente'), (cesta.models.FormaEntrega['VEINTICUATRO_HORAS'], '24 horas')], default=cesta.models.FormaEntrega['ESTANDAR'], max_length=50),
        ),
    ]
