# Generated by Django 4.1 on 2023-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0005_datospedido_forma_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospedido',
            name='forma_entrega',
            field=models.CharField(choices=[('EST', 'Estándar'), ('URG', 'Urgente'), ('24H', '24 horas')], default='EST', max_length=5),
        ),
    ]
