# Generated by Django 4.1 on 2023-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0006_alter_datospedido_forma_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospedido',
            name='forma_pago',
            field=models.CharField(choices=[('CONT', 'Contrareembolso')], default='CONT', max_length=10),
        ),
        migrations.AlterField(
            model_name='datospedido',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
