# Generated by Django 4.1 on 2023-11-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0007_datospedido_forma_pago_alter_datospedido_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospedido',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cesta.carrito'),
        ),
    ]
