# Generated by Django 4.1 on 2023-11-21 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cesta', '0008_alter_datospedido_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=12)),
                ('direccion_envio', models.CharField(max_length=150)),
                ('direccion_facturacion', models.CharField(max_length=150)),
                ('instrucciones_entrega', models.TextField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('forma_entrega', models.CharField(choices=[('EST', 'Estándar'), ('URG', 'Urgente'), ('24H', '24 horas')], default='EST', max_length=5)),
                ('forma_pago', models.CharField(choices=[('CONT', 'Contrareembolso')], default='CONT', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
