# Generated by Django 4.1 on 2023-11-22 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0009_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('LISTO', 'Listo'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En proceso')], default='EN_PROCESO', max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.TextField(default=''),
        ),
    ]
