# Generated by Django 4.1 on 2023-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0012_pedido_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospedido',
            name='forma_pago',
            field=models.CharField(choices=[('CONT', 'Contrareembolso'), ('STRIPE', 'Pago con Stripe')], default='CONT', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'Entregado'), ('CONFIRMADO', 'Confirmado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('CONT', 'Contrareembolso'), ('STRIPE', 'Pago con Stripe')], default='CONT', max_length=10),
        ),
    ]
