# Generated by Django 4.1 on 2023-12-02 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0015_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='secreto',
            field=models.CharField(default=uuid.UUID('209f4681-dcc4-4f36-bfd3-60d413dd3463'), max_length=255),
        ),
    ]
