# Generated by Django 4.1 on 2023-12-03 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0016_pedido_secreto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='secreto',
            field=models.CharField(default=uuid.UUID('6796a8e7-ffe3-4837-a8ad-f26b3f971c33'), max_length=255),
        ),
    ]
