# Generated by Django 4.1 on 2023-12-04 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0019_alter_pedido_secreto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='secreto',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
