# Generated by Django 4.1 on 2023-11-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_entrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosentrega',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosentrega',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datosentrega',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
