# Generated by Django 4.1 on 2023-11-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0012_pedido_precio'),
        ('factura', '0002_factura_productos_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='productos',
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cesta.pedido'),
            preserve_default=False,
        ),
    ]
