# Generated by Django 4.1 on 2023-11-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0012_pedido_precio'),
        ('factura', '0003_remove_factura_cliente_remove_factura_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesta.pedido'),
        ),
    ]
